### PR TITLE
Related app

### PR DESCRIPTION
**Pull request by avischerr**
@leal10 @rosemaling 

Updates:
- Added carousel for related products (#41)
- Added carousel for your outfit (#43)
- Added card to add product to outfit (#56)
- Added close functionality to modal window
- Action buttons are now dynamically rendering (star or x) (#53)
- Comparison modal dynamic rendering for product names
- Installed lodash in package.json (used in carousels)
- Refactored the way dummy data is pulled to better reflect API responses
- Added our project name to App.jsx as placeholder for nav bar :)
- Minor styling edits
- Cleaned up commented out code

Bugs:
- Throws error "Uncaught TypeError: outfit.push is not a function" on AddtoOutfitCard click (#56)
- Throws the following errors when opening modal (#55):
   - "Warning: Failed prop type: Invalid prop open of type function supplied to ForwardRef(Modal), expected boolean."
   - "Warning: Failed prop type: Invalid prop open of type function supplied to ForwardRef(SimpleBackdrop), expected boolean."
   - "Warning: Failed prop type: Invalid prop open of type function supplied to Unstable_TrapFocus, expected boolean."
   - "Warning: Received false for a non-boolean attribute show."

### CODE REVIEW

**Review by leal10 — COMMENTED** [review]
Looks Great @avischerr!! I would probably do more frequent pull request, since there is a lot of code here to review. Also I liked that you cleared a bunch of your code.

**Comment by avischerr** [comment]
Updates from yesterday's commits:

- Carousel widths aligned with visual guide
- Carousel cards no longer overlap on window resize
- Added a customer outfit array to state in App (I'm actually changing this to an object)
- Added remove from outfit functionality (I'm currently refactoring so method lives in App instead)
- Centered modal window in browser
- Centered product image in product cards
- Fixed errors associated with modal window
- In process of refactoring to prepare for API data (you'll see lots of commented out functions associated with this)
- Wireframing for related spec
- Added TODO comments for API requests in App

**Comment by avischerr** [comment]
@leal10 @rosemaling 

Updates: 

- Refactored current and selected products to be objects
- API requests implemented
- Added getProduct, getStyles and getRatingsMeta methods to App
- Added calculateRating method to App state
- Added currentId property to App state
- Headings rendering
- Related Products carousel rendering

Bugs:

- Still need to get Your Outfit carousel rendering
- Need to get Star Button rendering on Related Products cards
- Need to clean up code/remove comments and console.logs

**Comment by avischerr** [comment]
Closed, will open another pull request with new code.

**Pull request closed without merging**
